services:
  ingestion:
    build: ./services/ingestion
    ports:
      - "8001:8001"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - QDRANT_URL=http://qdrant:6333
    volumes:
      - tmp_data:/app/data
    depends_on:
      qdrant:
        condition: service_started
    restart: unless-stopped
    networks:
      - internal

  chat:
    build: ./services/chat
    ports:
      - "8002:8002"
    env_file: .env
    depends_on:
      qdrant:
        condition: service_started
      redis:
        condition: service_started
    restart: unless-stopped
    networks:
      - internal

  voice:
    build: ./services/voice
    ports:
      - "8003:8003"
    env_file: .env
    depends_on:
      chat:
        condition: service_started
    restart: unless-stopped
    networks:
      - internal

  frontend:
    build: ./services/frontend
    ports:
      - "8501:8501"
    env_file: .env
    depends_on:
      chat:
        condition: service_started
      ingestion:
        condition: service_started
      voice:
        condition: service_started
    restart: unless-stopped
    networks:
      - internal

  qdrant:
    image: qdrant/qdrant:v1.13.3
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    networks:
      - internal

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - internal

volumes:
  qdrant_data:
  tmp_data:

networks:
  internal:
    driver: bridge
